apiVersion: apps/v1
kind: Deployment
metadata:
 name: hpa-demo-app
spec:
 selector:
   matchLabels:
     run: hpa-demo-app
 replicas: 5
 template:
   metadata:
     labels:
       run: hpa-demo-app
   spec:
     containers:
     - name: hpa-demo-app
       image: us-docker.pkg.dev/gke-demos-345619/gke-demos/hpa-demo:latest
       resources:
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 512Mi
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: hpa-demo-service
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   run: hpa-demo-app