apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-demo-app
 minReplicas: 5
 maxReplicas: 40
 targetCPUUtilizationPercentage: 70